name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the latest code
      - name: Checkout code
        uses: actions/checkout@v3  # Latest version

      # Step 2: Create the SSH private key file
      - name: Create SSH key file
        run: |
          echo "${{ secrets.VPS_DEPLOY_KEY }}" > /tmp/vps_deploy_key
          chmod 600 /tmp/vps_deploy_key

      # Step 3: Deploy to VPS using the key file
      - name: Deploy to VPS
        run: |
          ssh -i /tmp/vps_deploy_key -o StrictHostKeyChecking=no valuebit-xposter@62.72.20.134 << 'EOF'
          cd /home/valuebit-xposter/htdocs/xposter.valuebit.net/xposter
          git pull origin main
          npm install
          npm run build
          pm2 restart astro-server
          EOF

      # Step 4: Clean up the SSH key file
      - name: Clean up
        run: |
          shred -u /tmp/vps_deploy_key  # Securely delete the key file
