name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the latest code
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version

      # Step 2: Set up SSH agent and add SSH key
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0  # Use the latest version
        with:
          ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

      # Step 3: Debug - List loaded SSH keys to verify the key is loaded
      - name: List Loaded SSH Keys
        run: ssh-add -l

      # Step 4: Deploy to VPS with SSH_AUTH_SOCK explicitly passed
      - name: Deploy to VPS
        env:
          SSH_AUTH_SOCK: ${{ steps.ssh-agent.outputs.ssh-agent-socket }}
        run: |
          ssh -T -vvv -o StrictHostKeyChecking=no -o "IdentitiesOnly=yes" -o "IdentityAgent=$SSH_AUTH_SOCK" valuebit-xposter@62.72.20.134 << 'EOF'
          cd /home/valuebit-xposter/htdocs/xposter.valuebit.net
          git pull origin main
          npm install
          npm run build
          pm2 restart astro-server
          EOF
